name: Build Lint and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: init submodules
      run: git submodule update --init --recursive

    - name: Install Neovim
      run: |
        # TODO: Pin to 11.0 once it's released
        curl -LSs https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz | tar xzf - -C "$HOME"
        echo "$HOME/nvim-linux-x86_64/bin" >> $GITHUB_PATH

    # Need a fresh install of rust and all its components for rust-analyzer to function properly
    - name: Rust toolchain uninstall (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        command -v rustup >/dev/null && rustup self uninstall -y

    - name: Rust toolchain uninstall (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        rm -rf ~/.cargo ~/.rustup
        brew uninstall rustup-init || true

    - name: Rust toolchain install
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    # NOTE: There's nothing particularly special about 1.87, we just pin to a
    # specific version to avoid unexpected breakages with each update. We *should*
    # keep the project in sync with rustc/rust-analyzer as they release new versions
    - name: Pin Rust to 1.87
      run: rustup default '1.87'

    - name: Add rust components
      run: |
        rustup component add rust-src rustfmt clippy rust-analyzer

    - name: Build
      run: cargo build --workspace

    - name: Lint
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

    - name: fmt
      run: cargo fmt --check

    - name: Run tests (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: cargo test

    - name: Run tests (MacOS)
      if: matrix.os == 'macos-latest'
      run: brew install expect

    - name: Run tests (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        unbuffer -noecho cargo test

    - name: Run tests (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        unbuffer -leaveopen cargo test

    - name: Install luals (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir "$HOME/luals"
        curl -LSs https://github.com/LuaLS/lua-language-server/releases/download/3.13.6/lua-language-server-3.13.6-linux-x64.tar.gz | tar xzf - -C "$HOME/luals"
        echo "$HOME/luals/bin" >> $GITHUB_PATH

    - name: Install luals (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        mkdir "$HOME/luals"
        curl -LSs https://github.com/LuaLS/lua-language-server/releases/download/3.13.6/lua-language-server-3.13.6-darwin-arm64.tar.gz | tar xzf - -C "$HOME/luals"
        echo "$HOME/luals/bin" >> $GITHUB_PATH

    - name: Lua lint
      run: |
        lua-language-server --check lspresso-shot/lua_templates/

    # Uncomment this to ssh into the runner and debug if needed
    # - name: Setup tmate session
    #   if: always()
    #   uses: mxschmitt/action-tmate@v3
